### ISSUE TITLE
Not working with Intel SSDPEKKF5512G8L

### ISSUE THREAD

**Issue by javierspn** [ken-yossy/nvmetool-win-powershell#1]
Hi Ken!

The script is not working for me with this disk's model:

INTEL SSDPEKKF5512G8L

Output:

![2021-08-04 09_55_59-Select Administrator_ Windows PowerShell](https://user-images.githubusercontent.com/18490381/128143850-30235b5e-fc2d-453a-b766-a2f823d42aac.png)

Mind lending a hand?

Thanks!

**Comment by ken-yossy** [comment]
Hi @javierspn,

> Mind lending a hand?

Sure!

> INTEL SSDPEKKF5512G8L

It's Intel SSD 760p Series (512GB, M.2 80mm), right?

Could you get SMART Log data with other tools (for example, by Crystal Disk Info like below)?
![nvme-smart2](https://user-images.githubusercontent.com/52020141/128153194-f48650b5-c9dd-4343-9347-9c15c4746c9b.png)

If you successfully retrieve SMART data, please edit the script (line 155) as follows and try again.

From:
``` $Property.ProtocolDataRequestSubValue   = [System.Convert]::ToUInt32("4294967295"); # Namespace ID (0xFFFFFFFF)```
to:
``` $Property.ProtocolDataRequestSubValue   = 0;```
or
``` $Property.ProtocolDataRequestSubValue   = 1;```

I hope it works...

Thank you,
Ken

**Comment by javierspn** [comment]
Heya Ken!

Blazing fast reply...thanks a lot.

It is an Intel® SSD Pro 7600p Series:

![image](https://user-images.githubusercontent.com/18490381/128159199-67a68202-dae8-4959-8d41-46527c2c6ce5.png)

It works with $Property.ProtocolDataRequestSubValue = 0;

![image](https://user-images.githubusercontent.com/18490381/128159310-df76313a-fda2-40b7-93b0-eb0291b67d34.png)

The issue: now I am testing it with a WD:

![Capture 549](https://user-images.githubusercontent.com/18490381/128162041-1bafef3a-3d22-47f3-8fa9-72d85c588701.PNG)

and it also fails:

![Capture2 550](https://user-images.githubusercontent.com/18490381/128162109-3780638d-5020-4d91-be9a-cd5fc3e07420.PNG)

I suspect that NVMe disks are so "new" that for each builder we have to go model by model (maybe) fixing the calls.

Regards,

**Comment by ken-yossy** [comment]
You got it! I'm glad to hear that!
And thank you for your further testing.

Did you run this script with $Property.ProtocolDataRequestSubValue = 0, with WD's ssd?
Probably, it will work without the change...
If so, it is because NVMe spec allows 0, 1, and 0xFFFFFFFF for ID of target namespace (NSID) to retrieve SMART data (Intel ignores NSID = 0xFFFFFFFF, and WD refuses NSID = 0).

> I suspect that NVMe disks are so "new" that for each builder we have to go model by model (maybe) fixing the calls.

Me too...if DeviceIoControl() fails, it can be possible to change NSID and re-issue DeviceIoControl() after the failure, but if it's ignored and returned all zero like Intel's ssd, verifying the retrieved data may be needed.

Regards,
Ken

**Comment by javierspn** [comment]
Hi Ken!

You are the man XD.

Yes, replacing to  $Property.ProtocolDataRequestSubValue = 0 did the trick.

Let me speak with a colleague that has much more command on this than me, he has been working with a CrystalDiskInfo dev and he  may have found a global solution for this...I will give you feedback if we can sort this out.

Thanks!

**Comment by javierspn** [comment]
Hi Ken!

Sorry for being too late to the party XD.

It seems that for now this has no easy solution. If we change  $Property.ProtocolDataRequestSubValue it works for some models and not for others...additionally, when the smart value is retrieved for a non-working disk it always gives us a Zero value, as if the disk is perfectly fine, when it isn't. And How do we know that this value is the actual one?...

Well...we don't know because the disk could be so new that the actual value is zero OR it could be that it is not being retrieved properly.

Lets pray to the Microsoft gods for them to implement a solution for this on their native P$ commands. But for now, unreliable.

Thanks anyway for your help!

**Comment by ken-yossy** [comment]
Thank you for your further report. Much appreciated!

There's a value that is considered to be affected to the behavior of the drive; bit 0 of Log Page Attribute (LPA) in Identify Controller Data Structure (Byte 261).
But, anyway, it's not easy nor smart!

I will take into account of this behavior in testing NVMe drives in future.

Thank you,
Ken

**Comment by ken-yossy** [comment]
Oh, I close this issue.

Thank you
