### ISSUE TITLE
Not reporting a temperature for Samsung 970 Evo Plus drive

### ISSUE THREAD

**Issue by andrico21** [ken-yossy/nvmetool-win-powershell#2]
Hi bud.

I have two different NVMe-drives in my laptop - WDC SN520 and Samsung 970 Evo Plus: for WDC your 'get-temperature' script works fine, but for Samsung the value it reports seems wrong: -273

```
Get-PhysicalDisk | where {$_.BusType -eq "NVMe"} | select DeviceId,FruId,Model,Size | ft

DeviceId FruId           Model                                 Size
-------- -----           -----                                 ----
1        19529C800089    WDC PC SN520 SDAPNUW-512G     512110190592
0        S6P1NS0T202661D Samsung SSD 970 EVO Plus 2TB 2000398934016


.\get-temperature.ps1 -dno 0
03:17:54,-273
.\get-temperature.ps1 -dno 1
03:17:56,47
```
any ideas to try?

**Comment by andrico21** [comment]
btw outputs of get-smart-log:
Samsung
```
.\get-smart-log.ps1 0
Critical Warning: 0x00
Composite Temperature: 315 (K)
Available Spare: 100 (%)
Available Spare Threshold: 10 (%)
Percentage Used: 0 (%)
Endurance Group Summary: 0x00
Data Unit Read: 0x00000000000765CF
Data Unit Written: 0x00000000004CE948
Host Read Commands: 0x0000000000B270EB
Host Write Commands: 0x0000000001188720
Controller Busy Time: 0x0000000000000014 (minutes)
Power Cycles: 0x0000000000000006
Power On Hours: 0x000000000000000B (hours)
Unsafe Shutdowns: 0x0000000000000000
Media and Data Integrity Errors: 0x0000000000000000
Number of Error Information Entries: 0x0000000000000000
Warning Composite Temperature Time: 0 (minutes)
Critical Composite Temperature Time: 0 (minutes)
Temperature Sensor 1: 315 (K)
Temperature Sensor 2: 324 (K)
Temperature Sensor 3: 0 (K)
Temperature Sensor 4: 0 (K)
Temperature Sensor 5: 0 (K)
Temperature Sensor 6: 0 (K)
Temperature Sensor 7: 0 (K)
Temperature Sensor 8: 0 (K)
Thermal Management Temperature 1 Transition Count: 0 (times)
Thermal Management Temperature 2 Transition Count: 0 (times)
Total Time For Thermal Management Temperature 1: 0 (seconds)
Total Time For Thermal Management Temperature 2: 0 (seconds)
```
WDC
```
.\get-smart-log.ps1 1
Critical Warning: 0x00
Composite Temperature: 327 (K)
Available Spare: 100 (%)
Available Spare Threshold: 10 (%)
Percentage Used: 2 (%)
Endurance Group Summary: 0x00
Data Unit Read: 0x00000000021093DA
Data Unit Written: 0x0000000002360423
Host Read Commands: 0x000000001AA41EF1
Host Write Commands: 0x0000000025DB5A99
Controller Busy Time: 0x00000000000005E8 (minutes)
Power Cycles: 0x00000000000002C2
Power On Hours: 0x00000000000016CA (hours)
Unsafe Shutdowns: 0x0000000000000011
Media and Data Integrity Errors: 0x0000000000000000
Number of Error Information Entries: 0x0000000000000000
Warning Composite Temperature Time: 4 (minutes)
Critical Composite Temperature Time: 0 (minutes)
Temperature Sensor 1: 0 (K)
Temperature Sensor 2: 0 (K)
Temperature Sensor 3: 0 (K)
Temperature Sensor 4: 0 (K)
Temperature Sensor 5: 0 (K)
Temperature Sensor 6: 0 (K)
Temperature Sensor 7: 0 (K)
Temperature Sensor 8: 0 (K)
Thermal Management Temperature 1 Transition Count: 0 (times)
Thermal Management Temperature 2 Transition Count: 0 (times)
Total Time For Thermal Management Temperature 1: 0 (seconds)
Total Time For Thermal Management Temperature 2: 0 (seconds)
```

**Comment by andrico21** [comment]
I've removed strings with the same absent commands for compact output

Samsung
```
.\get-command-supported.ps1 0

Scan result of Admin Command Set (X: supported)
[ X ] Delete I/O Submission Queue
[ X ] Create I/O Submission Queue
[ X ] Get Log Page
[ X ] Delete I/O Completion Queue
[ X ] Create I/O Completion Queue
[ X ] Identify
[ X ] Abort
[ X ] Set Features
[ X ] Get Features
[ X ] Asynchronous Event Request
[ X ] Firmware Commit
[ X ] Firmware Image Download
[ X ] Device Self-test
[ X ] Format NVM
[ X ] Security Send
[ X ] Security Receive
[ X ] Sanitize

Scan result of I/O and NVM Command Set (X: supported)
[ X ] Flush
[ X ] Write
[ X ] Read
[ X ] Write Uncorrectable
[ X ] Compare
[   ] Write Zeroes
[ X ] Dataset Management
```

WDC
WDC
```
.\get-command-supported.ps1 1

Scan result of Admin Command Set (X: supported)
[ X ] Delete I/O Submission Queue
[ X ] Create I/O Submission Queue
[ X ] Get Log Page
[ X ] Delete I/O Completion Queue
[ X ] Create I/O Completion Queue
[ X ] Identify
[ X ] Abort
[ X ] Set Features
[ X ] Get Features
[ X ] Asynchronous Event Request
[ X ] Firmware Commit
[ X ] Firmware Image Download
[ X ] Device Self-test
[ X ] Format NVM
[ X ] Security Send
[ X ] Security Receive
[   ] Sanitize

Scan result of I/O and NVM Command Set (X: supported)
[ X ] Flush
[ X ] Write
[ X ] Read
[ X ] Write Uncorrectable
[ X ] Compare
[ X ] Write Zeroes
[ X ] Dataset Management
```

**Comment by ken-yossy** [comment]
Hi,

Thank you for your report.

I don't have a Samsung 970 Evo Plus but I have encountered an error very similar to your report with Kioxia's NVMe drive on Windows 11 (see below). 
Not only with temperture.ps1, I have encountered the same error with get-smart-log.ps1 on Windows 11.
I will check it on Windows 11 at first, because I have not found such errors on Windows 10.

Ken 
![error](https://user-images.githubusercontent.com/52020141/178169408-7c3d7c7c-e4b0-4283-9940-fb482bbb44f9.png)

**Comment by ken-yossy** [comment]
I'm sorry that the error showed in the previous message was due to my mistake... correct physical drive no. was '1'. And the script successfully finished for the correct drive.

Also, I've got Samsung 970 EVO Plus (500 GB) and tested on Windows 10. It was succeeded as below (sorry for Japanese texts in the pic).
![screenshot-with-ss970evoplus](https://user-images.githubusercontent.com/52020141/178868463-54be5a0d-b2ba-47ce-bc71-9d7bad075bf8.png)

I fixed some incorrect usages of field in `NVMeStorageQueryProperty` in the latest change, so please test again with the latest version.
If you still have any problem, please let me know.

Thank you,
Ken

**Comment by andrico21** [comment]
> I fixed some incorrect usages of field in `NVMeStorageQueryProperty` in the latest change, so please test again with the latest version. If you still have any problem, please let me know.

Hi, yeah - now I'm confirming it works in Windows 11 x64 with Samsung drive too! thanks bud

**Comment by andrico21** [comment]
some idea to improve - not sure if it's possible to easily extract drive name and I wrote it in static way. Also output which Telegraf agent can consume for further shipping to InfluxDB or so...
```
$driveNames = @("Samsung SSD 970 EVO Plus 2TB","WDC PC SN520 SDAPNUW-512G")

do {
    $ret = GetCompositeTemperature $dno

    if ( $ret[0] -eq 0 ) { break }; # error
    if ( $inK -eq 0 ) { $ret[1] -= 273; } # in Celcius

    $date = Get-Date -Format "hh:mm:ss";
    if ( -not [String]::IsNullOrEmpty($of) ) {
        Write-Output( "NVMeTemps,drive=$dno temperature={0}" -F $ret[1] ) >> $of
    }
    Write-Host( "NVMeTemps,driveNo=$dno driveName=""$($drivenames[$dno])"" temperature={0}" -F $ret[1] );

    Start-Sleep -Seconds $pd
} while( $pd )
```

**Comment by ken-yossy** [comment]
> Hi, yeah - now I'm confirming it works in Windows 11 x64 with Samsung drive too! thanks bud

Great! It's my pleasure.
Also thank you for your idea.
I think this is very helpful to integrate such a drive monitoring task into system telemetry.
Because users can edit the string (format) for `Write-Host` to their preferred one.
I think it should be left for users and I should keep this script simple...

-- Ken

**Comment by andrico21** [comment]
> > Hi, yeah - now I'm confirming it works in Windows 11 x64 with Samsung drive too! thanks bud
> 
> Great! It's my pleasure.
> Also thank you for your idea.
> I think this is very helpful to integrate such a drive monitoring task into system telemetry.
> Because users can edit the string (format) for `Write-Host` to their preferred one.
> I think it should be left for users and I should keep this script simple...
> 
> -- Ken

Yup, I just posted it as example. Telegraf can accept it as InfluxDB Line Protocol formatted output (so that's exactly what I'm doing in example above) or JSON.
https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md

Then [exec input plugin](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/exec/README.md) is one who grabs it for further processing.

**Comment by ken-yossy** [comment]
> Yup, I just posted it as example. Telegraf can accept it as InfluxDB Line Protocol formatted output (so that's exactly what I'm doing in example above) or JSON. https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md

I've got it. I was misunderstanding.
Thank you for your explanation.

-- Ken
