### ISSUE TITLE
Could you extent the PhyDrvNo-Parameter?

### ISSUE THREAD

**Issue by Delapro** [ken-yossy/nvmetool-win-powershell#3]
I was playing around with your Powershell-NVME-Scripts. Great work!

But before being successful I had some trouble, because I was trying it on a remote test machine. I thought it already was upgraded with NVME but it still was on SATA :-)

So I always got the error

```Powershell
PS C:\Users\SCAN> get-command-supported -PhyDrvNo 0 -Verbose
[E] DeviceIoControl() failed: System.ComponentModel.Win32Exception (0x80004005): Die Anforderung konnte wegen eines E/A-Gerätefehlers nicht ausgeführt werden
```

After playing around and checking on other machines, I thought it would be great, the script automatically show the available NVME drives. So this would help:

```Powershell
$nvmeDrives=Get-PnpDevice | where { $_.InstanceId -like "SCSI\DISK&VEN_NVME&*"}
$physdisks = gwmi win32_diskdrive| where {$nvmeDrives.deviceid -Contains $_.pnpdeviceid}

# $physdisks.deviceid returns \\.\PHYSICALDRIVE0
```

It is not perfect, but I think you get the idea.

Please feel free to close this issue right away, because I just wanted to document the error I got for later reference.

**Comment by ken-yossy** [comment]
Hi @Delapro,

Thank you for your feedback!
I agree that the behavior (showing only error message of `DeviceIoControl`) isn't friendly for users who are trying to retrieve the information of remote drive...

> It is not perfect, but I think you get the idea.

Yes! your code provides me a concrete idea to check that the specified drive is really NVMe drive or not!
With this check, more friendly message can be provided when user specifies wrong drive no. (not NVMe drive)

I will prepare a machine with multiple NVMe drives and test the procedure.
And if it's fine, it will be merged.

Again, thank you for your feedback, and hope your happy playing!

Ken

**Comment by ken-yossy** [comment]
I close this ticket and I'll post a new ticket for it, thanks.
